export const SOME_ACTION = 'SOME_ACTION';
export const TOP_STORY_DATA = 'TOP_STORY_DATA';
export const FETCH_TOP_STORIES_ERROR = 'FETCH_TOP_STORIES_ERROR';
export const FETCH_TOP_STORIES_REQUEST = 'FETCH_TOP_STORIES_REQUEST';
